export const UPDATE_SCROLLED = "UPDATE_SCROLLED";
export const UPDATE_HAMCLICKED = "UPDATE_HAMCLICKED";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_PHONE = "UPDATE_PHONE";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
